name: Check all
on:
  pull_request:
jobs:
  check-all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Check Lint
        run: yarn lint

      - name: Build
        run: yarn build
        env:
          RPC_PROVIDER_URL_1: ${{ vars.RPC_PROVIDER_URL_1 }}
          RPC_PROVIDER_URL_5: ${{ vars.RPC_PROVIDER_URL_5 }}
          RPC_PROVIDER_URL_17000: ${{ vars.RPC_PROVIDER_URL_17000 }}
          WALLETCONNECT_PROJECT_ID: ${{ vars.WALLETCONNECT_PROJECT_ID }}
          SUPPORTED_CHAINS: ${{ vars.SUPPORTED_CHAINS }}
          DEFAULT_CHAIN: ${{ vars.DEFAULT_CHAIN }}
      - name: Check types
        run: yarn types

      - name: Tests
        run: yarn test
        env:
          TEST_PRIVATE_KEY: ${{ secrets.TEST_PRIVATE_KEY }}
          TEST_CHAIN_ID: ${{ vars.TEST_CHAIN_ID }}
          TEST_RPC_URL: ${{ secrets.TEST_RPC_URL }}
